### ISSUE TITLE
Ability to configure poolboy options

### ISSUE THREAD

**Issue by stuartc** [slashdotdash/eventstore#6]
At the moment, the Postgres workers pool defaults to 10. It would be nice to be able to change it.

I'd like to propose two keys: `pool_size` and `pool_max_overflow`.
Totally open to different names, and more than happy to do a PR for this.

**Comment by slashdotdash** [comment]
@stuartc Agreed, this would be a useful addition. Will accept a PR if you want to make the change, otherwise I'll add these when I get the chance. 

Have you seen the existing benchmarking suite? You can use that to get a rough idea which settings work best on your own hardware.

```
MIX_ENV=bench mix do es.reset, app.start, bench
````

I'm currently reworking the event persistence so that a single Elixir process is used for all event writing. This is to resolve the issue raised in #3. Work in progress is on the [single-writer](https://github.com/slashdotdash/eventstore/tree/single-writer) branch. This is a significant internal change, but there should be no impact to the consumer API.

The outcome of those changes is that the Poolboy configuration will only be used when reading from the database.

**Comment by stuartc** [comment]
Right, thats great! I'll throw those config keys in shortly.
For the most part I think the defaults are fine, was a concern on Heroku as they limit you to
20 connections on basic packages - which mixed with other things is a pretty low limit.
At least in my case Elixir will turn the instance to dust before hitting that limit. :)

**Comment by stuartc** [comment]
Thanks!
